# Scripts de extracción de datos
- Osvaldo Ceballos O. , Andrés Jimenez B.

In [44]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

import os
cwd= os.getcwd()
print (cwd)

/content

# 1.- Datos aduanas

### 2.1 Fuente Datos Abiertos Gobierno de Chile (Datos.gov.cl)

In [1]:
!pip install ckanapi requests openpyxl

Collecting ckanapi
  Downloading ckanapi-4.11-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: requests in c:\users\oaceb\anaconda3\lib\site-packages (2.32.5)
Requirement already satisfied: openpyxl in c:\users\oaceb\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: setuptools in c:\users\oaceb\anaconda3\lib\site-packages (from ckanapi) (80.9.0)
Collecting docopt (from ckanapi)
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: python-slugify>=1.0 in c:\users\oaceb\anaconda3\lib\site-packages (from ckanapi) (8.0.4)
Collecting simplejson (from ckanapi)
  Downloading simplejson-3.20.2-cp313-cp313-win_amd64.whl.metadata (3.4 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\oaceb\anaconda3\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\oaceb\anaconda3\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\oaceb\anaconda3\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\oaceb\anaconda3\lib\site-packages (from requests) (2025.11.12)
Requirement already satisfied: et-xmlfile in c:\users\oaceb\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\oaceb\anaconda3\lib\site-packages (from python-slugify>=1.0->ckanapi) (1.3)
Downloading ckanapi-4.11-py3-none-any.whl (50 kB)
Downloading simplejson-3.20.2-cp313-cp313-win_amd64.whl (75 kB)
Building wheels for collected packages: docopt
  Building wheel for docopt (pyproject.toml): started
  Building wheel for docopt (pyproject.toml): finished with status 'done'
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13856 sha256=17d19b3ce802643c4b3ba95d152ff91d3051620fc5683a14d4928f0dc90067aa
  Stored in directory: c:\users\oaceb\appdata\local\pip\cache\wheels\0b\1d\03\175286677fb5a1341cc3e4755bf8ec0ed08f3329afd67446b0
Successfully built docopt
Installing collected packages: docopt, simplejson, ckanapi

   ------------- -------------------------- 1/3 [simplejson]
   ---------------------------------------- 3/3 [ckanapi]

Successfully installed ckanapi-4.11 docopt-0.6.2 simplejson-3.20.2

In [3]:
import urllib
from ckanapi import RemoteCKAN
import requests
import pandas as pd
import numpy as np

In [7]:
# URL del portal CKAN
ckan_url = 'https://datos.gob.cl/'

# Conexión al portal CKAN
ckan = RemoteCKAN(ckan_url)

# Realizar una búsqueda de datasets
query = 'Registros de Importación'  #@param
results = ckan.action.package_search(q=query)

# Mostrar nombres y descripciones de los primeros datasets encontrados
for dataset in results['results']:
    print(f"Nombre: {dataset['title']}")
    print(f"Descripción: {dataset['notes']}")
    print(f"Id: {dataset['id']}\n")

Nombre: Registros de Importación 2010
Descripción: Muestra el registro de ítems correspondientes a las declaraciones de ingreso (DIN) del año 2010. Registros mensuales.
Id: ed97ca95-b74e-4182-850a-d23e515d3b23

Nombre: Registros de Importación 2014
Descripción: Muestra el registro de ítems correspondientes a las declaraciones de ingreso (DIN) del año 2014. Registros mensuales.
Id: 097803f9-333b-4cc4-a07a-a1d0bc15fbdd

Nombre: Registros de Importación 2015
Descripción: Muestra el registro de ítems correspondientes a las declaraciones de ingreso (DIN) del año 2015.
Registros mensuales.

Id: da62712a-eecd-451c-9015-fd8803a45407

Nombre: Registros de Importación 2007
Descripción: Muestra el registro de ítems correspondientes a las declaraciones de ingreso (DIN) del año 2007. Registros mensuales.
Id: 15fa27c6-efc7-4960-9833-56d36dacd303

Nombre: Registro de Importación 2019
Descripción: Muestra el registro de ítems correspondientes a las declaraciones de ingreso (DIN) del año 2019. Registros mensuales. Formato comprimido  winrar.
Para poder hacer uso del archivo, es necesaria la descarga de todas las partes de un mismo mes.
Id: 3d7848c1-b1f1-46a0-b147-8e9f83767433

Nombre: Registros de Importación 2017
Descripción: Muestra el registro de ítems correspondientes a las declaraciones de ingreso (DIN) del año 2017. Registros mensuales. Formato comprimido  winrar.
Para poder hacer uso del archivo, es necesaria la descarga de todas las partes de un mismo mes.
Id: b3ce7942-bf2c-4ab9-ba25-ebc730396b6d

Nombre: Registros de Importación 2016
Descripción: Muestra el registro de ítems correspondientes a las declaraciones de ingreso (DIN) del año 2016. Registros mensuales. Formato comprimido  winrar.
Id: 5cfcd596-d425-4d07-8044-75d70c893325

Nombre: Registro de Importación 2022
Descripción: Muestra el registro de ítems correspondientes a las declaraciones de ingreso (DIN) del año 2022. Registros mensuales. Formato comprimido  winrar.
Para poder hacer uso del archivo, es necesaria la descarga de todas las partes de un mismo mes.
Id: 2538ffb0-402f-4fbf-a706-5f7fbe271670

Nombre: Registros de Importación 2013
Descripción: Muestra el registro de ítems correspondientes a las declaraciones de ingreso (DIN) del año 2013. Registros mensuales. Formato comprimido  winrar.
Id: 179f0a6b-0898-4060-8433-5c10a7553af0

Nombre: Registro de Importación 2021
Descripción: Muestra el registro de ítems correspondientes a las declaraciones de ingreso (DIN) del año 2021. Registros mensuales. Formato comprimido  winrar.
Para poder hacer uso del archivo, es necesaria la descarga de todas las partes de un mismo mes.
Id: ad202066-18e6-42dd-b70b-1991774656b5

In [ ]:
import os
import requests
from urllib.parse import urlparse, unquote

data_dir = os.path.abspath(os.path.join(os.getcwd(), "..", "data"))
os.makedirs(data_dir, exist_ok=True)

for dataset in results['results']:
    dataset_id = dataset['id']

    # Obtener detalles del dataset
    dataset_sub = ckan.action.package_show(id=dataset_id)

    # Mostrar información relevante
    print(f"Nombre: {dataset['title']}")
    print(f"Descripción: {dataset['notes']}")
    print(f"Recursos disponibles:")

    for resource in dataset_sub['resources']:
        resource_url = resource.get('url')
        resource_name = resource.get('name') or 'recurso'
        print(f"- {resource_name}: {resource.get('format')} ({resource_url})")

        if not resource_url:
            continue

        parsed_url = urlparse(resource_url)
        filename = os.path.basename(parsed_url.path) or f"{resource_name}"
        filename = unquote(filename)
        file_path = os.path.join(data_dir, filename)

        response = requests.get(resource_url, stream=True, timeout=120)
        response.raise_for_status()

        with open(file_path, "wb") as f:
            for chunk in response.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)

Nombre: Registros de Importación 2010
Descripción: Muestra el registro de ítems correspondientes a las declaraciones de ingreso (DIN) del año 2010. Registros mensuales.
Recursos disponibles:
- Enero 2010 Importaciones  1/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/5c60b560-478f-45ed-abcd-d657f1b5fcba/download/ene-2010-importaciones.part01.rar)
- Enero 2010 Importaciones 2/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/3f669ebe-320a-4a63-adde-51d12d4bd484/download/ene-2010-importaciones.part02.rar)
- Enero 2010 Importaciones 3/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/6409a407-5775-4e04-95fa-24b2602564d2/download/ene-2010-importaciones.part03.rar)
- Enero 2010 Importaciones 4/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/bfbe97c1-06bd-4c55-a9af-4acf360606a2/download/ene-2010-importaciones.part04.rar)
- Febrero 2010 Importaciones  1/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/e8730e7d-2b39-4928-a842-3a9e306dfc9e/download/feb-2010-importaciones.part01.rar)
-  Febrero 2010 Importaciones  2/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/1948ed93-9a82-4c6f-b6f3-1ba4a13866cb/download/feb-2010-importaciones.part02.rar)
- Febrero 2010 Importaciones  3/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/7a7f9557-a3a7-499f-b798-7e6fe01e3754/download/feb-2010-importaciones.part03.rar)
- Febrero 2010 Importaciones   4/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/cc473e54-b300-4b8c-80e3-a23cc8a838a4/download/feb-2010-importaciones.part04.rar)
- Marzo 2010 Importaciones 1/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/f9a895f5-0db5-4b0a-95b2-5a0dce6b1481/download/mar-2010-importaciones.part01.rar)
- Marzo 2010 Importaciones 2/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/9ed17871-139f-41af-b790-956b45899a8e/download/mar-2010-importaciones.part02.rar)
- Marzo 2010 Importaciones 3/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/4b18bfe8-341d-48a0-981c-96f44fcfd405/download/mar-2010-importaciones.part03.rar)
- Marzo 2010 Importaciones 4/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/2f5b4e47-1a71-40b3-bef0-a8f793f731e6/download/mar-2010-importaciones.part04.rar)
- Abril 2010 Importaciones 1/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/501fc9e6-8f43-45a3-9ed6-58ce9c32785c/download/abr-2010-importaciones.part01.rar)
- Abril 2010 Importaciones 2/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/e73a234e-e2b0-40f9-8a4c-5b19b2084347/download/abr-2010-importaciones.part02.rar)
- Abril 2010 Importaciones 3/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/bb88a1a0-0f86-4c7e-84a8-46bb0c0ef908/download/abr-2010-importaciones.part03.rar)
- Abril 2010 Importaciones 4/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/5474a30c-5344-40c4-bb95-ee9fafbc02c1/download/abr-2010-importaciones.part04.rar)
- Mayo 2010 Importaciones 1/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/666e17ec-77c1-428b-a6b5-3f71c8eb42de/download/may-2010-importaciones.part01.rar)
- Mayo 2010 Importaciones 2/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/27d65e39-59f4-411c-af16-978d756aebef/download/may-2010-importaciones.part02.rar)
- Mayo 2010 Importaciones 3/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/b956f4c7-c4c1-4a83-9694-8acda7b90910/download/may-2010-importaciones.part03.rar)
- Mayo 2010 Importaciones 4/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/5d2d32f1-4180-442e-b229-3f4aa927ccd3/download/may-2010-importaciones.part04.rar)
- Junio 2010 Importaciones 1/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/b2eb566d-9b06-4676-9409-168792578972/download/jun-2010-importaciones.part01.rar)
- Junio 2010 Importaciones 2/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/52f12da4-fd85-45de-b84e-0fcd5571ad2a/download/jun-2010-importaciones.part02.rar)
- Junio 2010 Importaciones 3/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/16c31cc3-82fd-49bb-af83-83aa6e9fb9a2/download/jun-2010-importaciones.part03.rar)
- Junio 2010 Importaciones 4/4: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/638ccf6e-460f-4187-a3fa-f5c0369557d4/download/jun-2010-importaciones.part04.rar)
- Julio 2010 Importaciones  1/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/c95f76e9-71da-4650-b964-8bbd2368c111/download/jul-2010-importaciones.part01.rar)
- Julio 2010 Importaciones  2/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/c728425f-300a-4603-9955-33dda9cf3d41/download/jul-2010-importaciones.part02.rar)
- Julio 2010 Importaciones  3/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/766ac42d-3956-4beb-8ae3-2979c24121e6/download/jul-2010-importaciones.part03.rar)
- Julio 2010 Importaciones  4/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/114b0426-8fd4-4913-8119-7587eb7287f8/download/jul-2010-importaciones.part04.rar)
- Julio 2010 Importaciones  5/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/8376ea9c-a843-4387-bd63-73f33db5b6ea/download/jul-2010-importaciones.part05.rar)
- Agosto 2010 Importaciones  1/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/44478ae5-1561-4dfb-a7f1-33fb5c510ac0/download/ago-2010-importaciones.part01.rar)
- Agosto 2010 Importaciones  2/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/5c387688-4fe4-4efc-93ef-7e7dcadf481b/download/ago-2010-importaciones.part02.rar)
- Agosto 2010 Importaciones  3/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/fd06d0c5-a7cd-4b1b-b252-e628fd79ad4c/download/ago-2010-importaciones.part03.rar)
- Agosto 2010 Importaciones  4/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/aae14c45-827c-4636-b9ec-f972fee08e0b/download/ago-2010-importaciones.part04.rar)
- Agosto 2010 Importaciones  5/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/1d08e58f-fc11-459e-856e-3e2d8a2e9a92/download/ago-2010-importaciones.part05.rar)
- Septiembre 2010 Importaciones 1/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/cf0a2b7a-b7b3-43e1-8004-53136da596d1/download/sep-2010-importaciones.part01.rar)
- Septiembre 2010 Importaciones 2/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/e95cc87c-4afd-4d0f-b56f-6b39994d1884/download/sep-2010-importaciones.part02.rar)
- Septiembre 2010 Importaciones 3/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/608d8a10-cf0b-42d0-ad0e-37e260f22f8e/download/sep-2010-importaciones.part03.rar)
- Septiembre 2010 Importaciones 4/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/d1ab0aea-121b-471a-8ff6-bc13fdcf97fa/download/sep-2010-importaciones.part04.rar)
- Septiembre 2010 Importaciones  5/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/7da316a8-82aa-4745-a802-6d45db505a77/download/sep-2010-importaciones.part05.rar)
- Octubre 2010 Importaciones 1/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/222b8f8b-c6d2-4073-b20b-035d5ec78ace/download/oct-2010-importaciones.part01.rar)
- Octubre 2010 Importaciones 2/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/a6bbe40d-06a9-4a93-b5ae-9ddf6840e709/download/oct-2010-importaciones.part02.rar)
- Octubre 2010 Importaciones  3/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/166cfd88-1563-46a9-aaad-4013ef5b23e8/download/oct-2010-importaciones.part03.rar)
- Octubre 2010 Importaciones  4/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/57a689b6-85ff-46c4-8b99-1c8d7818a996/download/oct-2010-importaciones.part04.rar)
- Octubre 2010 Importaciones  5/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/d5f38be9-a2ab-4695-94a9-f6156cf8b8b5/download/oct-2010-importaciones.part05.rar)
- Noviembre 2010 Importaciones 1/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/8d80a69b-3662-4c79-abd2-88d94ec50366/download/nov-2010-importaciones.part01.rar)
- Noviembre 2010 Importaciones 2/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/eabf7978-a073-4c0b-81af-436afd210a61/download/nov-2010-importaciones.part02.rar)
- Noviembre 2010 Importaciones 3/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/a7fbfb5e-deaf-4225-82b6-e124b54a0233/download/nov-2010-importaciones.part03.rar)
- Noviembre 2010 Importaciones 4/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/0006574d-33dc-456b-981d-8a119e1bb935/download/nov-2010-importaciones.part04.rar)
- Noviembre 2010 Importaciones 5/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/6fd3975d-8542-43e8-a08b-6f07d71fe2b0/download/nov-2010-importaciones.part05.rar)
- Diciembre 2010 Importaciones  1/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/0dd189b5-7a5b-4df8-889a-1009d5fd996c/download/dic-2010-importaciones.part01.rar)
- Diciembre 2010 Importaciones  2/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/1540db23-7a77-4319-9a66-26a7d19253e7/download/dic-2010-importaciones.part02.rar)
- Diciembre 2010 Importaciones  3/5: rar (https://datos.gob.cl/dataset/ed97ca95-b74e-4182-850a-d23e515d3b23/resource/628d9886-c6cd-4869-801e-81e6b9726d63/download/dic-2010-importaciones.part03.rar)

In [ ]:
# URL del recurso CSV
csv_url = 'https://datos.gob.cl/dataset/ccb5c078-d950-48f4-900b-d7fa4be21b07/resource/1d7ec097-9727-410f-a2ea-da7622d95b85/download/listado-sector-centro.xlsx'  #@param

# Descargar y cargar en un DataFrame de Pandas
aduanas_df = pd.read_excel(csv_url)

# Mostrar las primeras filas del DataFrame
parques_centro_df.head()

/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,N°,AREA VERDES,UBICACIÓN,m2
0,1.0,EL COIGUE DE MAGALLANES,EL COIGUE DE MAGALLANES / VILLA JARDINES DE ...,1541.0
1,2.0,PARQUE LA VIÑA DE LO CAÑAS,ROJAS MAGALLANES / AV. S. FONTECILLA / EL H...,8847.0
2,3.0,EL COIGUE DE CHILOE,CALLE EL C. DE CHILOE - VILLA LOS JARDINES D...,1661.0
3,4.0,PARQUE DE LA VIÑA,LAS ARAUCARIAS SUR / LAS NALCAS SUR,7938.0
4,5.0,ARRAYAN ROJO,LAS ARAUCARIAS SUR,868.0

### 2.2 Banco Central de Chile

In [ ]:
!pip install bcchapi

Collecting bcchapi
  Downloading bcchapi-1.1.2-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from bcchapi) (2.1.4)
Requirement already satisfied: requests>=2.0.1 in /usr/local/lib/python3.10/dist-packages (from bcchapi) (2.32.3)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->bcchapi) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->bcchapi) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->bcchapi) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->bcchapi) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.0.1->bcchapi) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.0.1->bcchapi) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.0.1->bcchapi) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.0.1->bcchapi) (2024.7.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->bcchapi) (1.16.0)
Downloading bcchapi-1.1.2-py3-none-any.whl (10 kB)
Installing collected packages: bcchapi
Successfully installed bcchapi-1.1.2

In [ ]:
import bcchapi

# Incluyendo credenciales explícitamente
# O bien llamando a un archivo
#siete = bcchapi.Siete(file="credenciales.txt")

In [ ]:
siete.buscar("M1")

,seriesId,frequencyCode,spanishTitle,englishTitle,firstObservation,lastObservation,updatedAt,createdAt
0,F021.M1.PRO.N.CLP.0.M,MONTHLY,"Agregados monetarios nominales saldos, M1 (Mil...","Balances nominal monetary aggregates, M1",1986-01-01,2024-07-01,2024-08-07,2024-08-07
1,F021.M1.PRO.N.CLP.1.M,MONTHLY,"Agregados monetarios nominales saldos, M1 dese...","Balances nominal monetary aggregates, M1 seaso...",1986-01-01,2024-07-01,2024-08-07,2024-08-07
2,F021.M1.STO.N.CLP.0.M,MONTHLY,"M1; agregados monetarios nominales, promedios ...","M1; nominal monetary aggregates, averaged (bil...",1965-12-01,2024-07-01,2024-08-07,2024-08-07
3,F021.M1.STO.N.CLP.HIST.M,MONTHLY,"Agregados monetarios nominales promedios, M1, ...",Base monetaria y agregados monetarios privados...,1965-12-01,2014-12-01,2015-05-28,2015-02-09
4,F021.M1.STO.R.P96.0.M,MONTHLY,"Agregados monetarios promedios reales , M1","Average real monetary aggregates, M1",1986-01-01,2023-12-01,2024-01-08,2024-01-08
5,F021.M1.STO.R.P96.1.M,MONTHLY,"Agregados monetarios promedios reales , M1 des...","Average real monetary aggregates, seasonally a...",1986-01-01,2023-12-01,2024-01-08,2024-01-08
6,F021.M1.STO.R.P96R23.0.M,MONTHLY,"M1 : Stock : Real : Pesos del 1996, referencia...","M1: Stock: Real: 1996 pesos, reference 2023: N...",1986-01-01,2024-07-01,2024-08-08,2024-08-08
7,F021.M1.STO.R.P96R23.1.M,MONTHLY,"M1 : Stock : Real : Pesos del 1996, referencia...","M1: Stock: Real: 1996 pesos, reference 2023: S...",1986-01-01,2024-07-01,2024-08-08,2024-08-08
8,F021.M1.STO.N.CLP.0.D,DAILY,Base monetaria y agregados monetarios privados...,Components of M1 (billions of pesos). M1,2011-01-03,2024-07-31,2024-08-07,2024-08-07
9,F021.M1.STS.N.CLP.0.D,DAILY,Base monetaria y agregados monetarios privados...,Base monetaria y agregados monetarios privados...,1996-01-07,2024-08-07,2024-08-16,2024-08-16
10,F021.M1.PPIB18.N.CLP.0.T,QUARTERLY,"M1/PIB (M1 como porcentaje del PIB, últimos 12...","M1/GDP (M1 as percentage of GDP, last 12 month...",1996-10-01,2024-04-01,2024-08-19,2024-08-19

In [ ]:
series_bc = siete.cuadro(
  series=["F032.IMC.IND.Z.Z.EP18.Z.Z.0.M", "G073.IPC.IND.2018.M","F021.M1.STO.N.CLP.0.M"],
  nombres = ["imacec", "ipc","M1"],
  desde="2010-01-01",
  hasta="2024-07-01",
  #variacion=12,
  frecuencia="M",
  observado={"imacec":"mean", "ipc":"last", "M1":"mean"}
)

In [ ]:
series_bc = series_bc.fillna(0)
series_bc.head(50)

               imacec        ipc            M1
2010-01-31  72.478647  76.458780  13780.600000
2010-02-28  69.784256  76.673627  13876.100000
2010-03-31  75.714061  76.738097  14204.700000
2010-04-30  77.836154  77.092780  14333.800000
2010-05-31  77.265080  77.370183  15026.700000
2010-06-30  76.186444  77.370465  15322.400000
2010-07-31  74.112635  77.867485  15145.300000
2010-08-31  77.296543  77.790935  15125.600000
2010-09-30  75.050155  78.102046  15648.800000
2010-10-31  80.061679  78.178624  15449.000000
2010-11-30  82.742488  78.233650  15348.200000
2010-12-31  85.153296  78.325874  16105.400000
2011-01-31  78.010367  78.537898  16485.800000
2011-02-28  74.279065  78.718604  16097.900000
2011-03-31  84.796447  79.320558  16026.500000
2011-04-30  82.417455  79.573557  16301.500000
2011-05-31  82.970070  79.891725  16579.600000
2011-06-30  80.371445  80.027306  16707.000000
2011-07-31  77.225680  80.128912  16298.700000
2011-08-31  80.761007  80.258840  16532.000000
2011-09-30  78.670318  80.657742  16812.000000
2011-10-31  84.178776  81.049265  16918.100000
2011-11-30  86.446294  81.306442  16806.400000
2011-12-31  91.043493  81.801767  18009.100000
2012-01-31  82.488508  81.873766  18188.313000
2012-02-29  79.583913  82.191760  17736.091000
2012-03-31  89.288491  82.325895  17863.384000
2012-04-30  87.623529  82.367637  18269.813000
2012-05-31  88.038617  82.392904  18738.816000
2012-06-30  86.063196  82.148901  18430.396000
2012-07-31  82.963263  82.138100  18339.818000
2012-08-31  86.650826  82.319751  17808.110000
2012-09-30  82.730095  82.952429  18638.737000
2012-10-31  89.847446  83.415861  18312.797000
2012-11-30  91.596477  83.040175  18272.034000
2012-12-31  94.690431  83.018130  19598.416000
2013-01-31  86.555400  83.165705  20113.553000
2013-02-28  82.225784  83.263246  19635.841758
2013-03-31  92.977186  83.582811  19926.323373
2013-04-30  91.412940  83.178497  19991.962000
2013-05-31  90.696062  83.171388  20370.534000
2013-06-30  88.606093  83.703908  20773.986000
2013-07-31  85.534996  83.922140  20848.742550
2013-08-31  88.926432  84.124095  20444.907000
2013-09-30  85.273742  84.575619  21103.844909
2013-10-31  92.340598  84.696262  20400.657982
2013-11-30  94.497923  85.011592  20803.212132
2013-12-31  96.977894  85.520647  22111.893000
2014-01-31  88.060444  85.673733  22353.752700
2014-02-28  84.785719  86.090681  22108.398000