# Scripts de extracción de datos
- Osvaldo Ceballos O. , Andrés Jimenez B.

In [7]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

import os
cwd= os.getcwd()
print (cwd)

C:\Users\oaceb\PycharmProjects\AnalisisLogisitca\src

# 1.- Datos aduanas

### 2.1 Fuente Datos Abiertos Gobierno de Chile (Datos.gov.cl)
https://datos.gob.cl/organization/servicio_nacional_de_aduanas

In [8]:
!pip install ckanapi requests openpyxl

Requirement already satisfied: ckanapi in c:\users\oaceb\anaconda3\lib\site-packages (4.11)
Requirement already satisfied: requests in c:\users\oaceb\anaconda3\lib\site-packages (2.32.5)
Requirement already satisfied: openpyxl in c:\users\oaceb\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: setuptools in c:\users\oaceb\anaconda3\lib\site-packages (from ckanapi) (80.9.0)
Requirement already satisfied: docopt in c:\users\oaceb\anaconda3\lib\site-packages (from ckanapi) (0.6.2)
Requirement already satisfied: python-slugify>=1.0 in c:\users\oaceb\anaconda3\lib\site-packages (from ckanapi) (8.0.4)
Requirement already satisfied: simplejson in c:\users\oaceb\anaconda3\lib\site-packages (from ckanapi) (3.20.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\oaceb\anaconda3\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\oaceb\anaconda3\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\oaceb\anaconda3\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\oaceb\anaconda3\lib\site-packages (from requests) (2025.11.12)
Requirement already satisfied: et-xmlfile in c:\users\oaceb\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\oaceb\anaconda3\lib\site-packages (from python-slugify>=1.0->ckanapi) (1.3)

In [9]:
import urllib
from ckanapi import RemoteCKAN
import requests
import pandas as pd
import numpy as np

In [12]:
# URL del portal CKAN
ckan_url = 'https://datos.gob.cl/'

# Conexión al portal CKAN
ckan = RemoteCKAN(ckan_url)

# Realizar una búsqueda de datasets
query = '(DUS) del año 202'  #@param
results = ckan.action.package_search(q=query)

# Mostrar nombres y descripciones de los primeros datasets encontrados
for dataset in results['results']:
    print(f"Nombre: {dataset['title']}")
    print(f"Descripción: {dataset['notes']}")
    print(f"Id: {dataset['id']}\n")

Nombre: Registro de Exportaciones 2026
Descripción: Muestra el registro de ítems correspondientes a los Documentos únicos de Salida (DUS) del año 2026. Registros mensuales. Formato comprimido WinRar.
Id: f6a643e7-a2e4-48e4-866e-732c7ceb51f3

Nombre: Registros de Exportación 2018
Descripción: Muestra el registro de ítem correspondientes a los Documentos Únicos de Salida (DUS) del año 2018. Registros mensuales.
Id: c9ddc990-53d9-4e50-86f0-d4b71cc6c803

Nombre: Registro de Exportaciones 2024
Descripción: Muestra el registro de ítems correspondientes a los Documentos únicos de Salida (DUS) del año 2024. Registros mensuales. Formato comprimido  WinRar.
Id: 1545f888-3490-466b-b815-60a0cd02ad23

Nombre: Registro de Exportación 2023
Descripción: Muestra el registro de ítems correspondientes a los Documentos únicos de Salida (DUS) del año 2023. Registros mensuales. Formato comprimido  WinRar.
Id: d4f8a96f-c555-4f68-b0a9-261dbd34292d

Nombre: Registro de Exportación 2021
Descripción: Muestra el registro de ítems correspondientes a los Documentos únicos de Salida (DUS) del año 2021. Registros mensuales. Formato comprimido  WinRar.
Id: 4cafbdb0-d931-4e8a-b354-53ce263f9dea

Nombre: Registro de Exportación 2020
Descripción: Muestra el registro de ítems correspondientes a los Documentos únicos de Salida (DUS) del año 2020. Registros mensuales. Formato comprimido  WinRar.
Id: 8ffb8730-8408-4db1-8217-c0fa2a955cff

Nombre: Registros de exportación 2013
Descripción: Muestra el registro de ítems correspondientes a los Documentos Unicos de Salida (DUS) del año 2013. Registros mensuales.
Id: eb1c91f2-6aa3-4611-a20e-4117141a2755

Nombre: Registros de exportación 2009
Descripción: Muestra el registro de ítems correspondientes a los Documentos Unicos de Salida (DUS) del año 2009. Registros mensuales.
Id: cab89a89-ab7e-42eb-95b2-06f26b8d3aae

Nombre: Registros de exportación 2010
Descripción: Muestra el registro de ítems correspondientes a los Documentos Unicos de Salida (DUS) del año 2010. Registros mensuales.
Id: eea4a210-e5a5-4ef5-a1d4-6e2a40c3aa7c

Nombre: Registro de Exportación 2022
Descripción: Muestra el registro de ítems correspondientes a los Documentos únicos de Salida (DUS) del año 2022. Registros mensuales. Formato comprimido  WinRar.
Id: 8d91a332-8c94-492a-8192-9a59fcd87681

In [13]:
import os
import requests
from urllib.parse import urlparse, unquote

data_dir = os.path.abspath(os.path.join(os.getcwd(), "..", "data"))
os.makedirs(data_dir, exist_ok=True)

for dataset in results['results']:
    dataset_id = dataset['id']

    # Obtener detalles del dataset
    dataset_sub = ckan.action.package_show(id=dataset_id)

    # Mostrar información relevante
    print(f"Nombre: {dataset['title']}")
    print(f"Descripción: {dataset['notes']}")
    print(f"Recursos disponibles:")

    for resource in dataset_sub['resources']:
        resource_url = resource.get('url')
        resource_name = resource.get('name') or 'recurso'
        print(f"- {resource_name}: {resource.get('format')} ({resource_url})")

        if not resource_url:
            continue

        parsed_url = urlparse(resource_url)
        filename = os.path.basename(parsed_url.path) or f"{resource_name}"
        filename = unquote(filename)
        file_path = os.path.join(data_dir, filename)

        response = requests.get(resource_url, stream=True, timeout=120)
        response.raise_for_status()

        with open(file_path, "wb") as f:
            for chunk in response.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)

Nombre: Registro de Exportaciones 2026
Descripción: Muestra el registro de ítems correspondientes a los Documentos únicos de Salida (DUS) del año 2026. Registros mensuales. Formato comprimido WinRar.
Recursos disponibles:
- Metadata Exportaciones: xlsx (https://datos.gob.cl/dataset/f6a643e7-a2e4-48e4-866e-732c7ceb51f3/resource/e0a25239-af2f-49be-afc3-44be524d6e4e/download/descripcion-y-estructura-de-datos-.xlsx)
- Exportaciones enero 2026: rar (https://datos.gob.cl/dataset/f6a643e7-a2e4-48e4-866e-732c7ceb51f3/resource/e8075003-9f64-4e3a-aa7e-f689a7e056eb/download/exportaciones-enero-2026.rar)
- Exportaciones enero 2026 – Bultos: rar (https://datos.gob.cl/dataset/f6a643e7-a2e4-48e4-866e-732c7ceb51f3/resource/6dd1316e-fe99-4a62-80c2-d838dcb3695a/download/exportaciones-enero-2026-bultos.rar)
- Exportaciones enero 2026 – Documentos de Transporte: rar (https://datos.gob.cl/dataset/f6a643e7-a2e4-48e4-866e-732c7ceb51f3/resource/f15ca5c2-ee96-4d47-be9b-61ca677ab4d7/download/exportaciones-enero-2026-documentos-de-transporte.rar)
Nombre: Registros de Exportación 2018
Descripción: Muestra el registro de ítem correspondientes a los Documentos Únicos de Salida (DUS) del año 2018. Registros mensuales.
Recursos disponibles:
- Metadata Exportaciones: xlsx (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/4eaebc3a-a313-4670-83ef-ace5decfc31f/download/descripcion-y-estructura-de-datos-dus.xlsx)
- Enero 2018 – Exportaciones: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/8d258853-e863-4044-a5f7-000155e8d8ef/download/2018-ene-expo.rar)
- Enero 2018 - Exportaciones-BULTOS: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/b6de50ac-3b60-49f0-bfb3-05a1307d9b6b/download/2018-ene-expo-bultos.rar)
- Enero 2018 - Exportaciones-Dtran: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/4b453426-f9e9-4e1f-9980-120e0b0a92b5/download/infodusdtransinenero-2018.rar)
- Febrero 2018 – Exportaciones: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/be7d836f-03ba-4422-a52e-661287c18de0/download/2018-feb-expo.rar)
- Febrero 2018 - Exportaciones-BULTOS: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/ea8dd5d8-de0c-4143-82a6-05f5dfad8e79/download/2018-feb-expo-bultos.rar)
- Febrero 2018 - Exportaciones-Dtran: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/83eba1b8-4a7d-4c4d-be91-8606415ba0b7/download/2018-feb-expo-dtran.rar)
- Marzo 2018- Exportaciones: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/6fd61f68-f4d9-41a4-b1bd-2fcad2801b7f/download/2018-mar-expo.rar)
- Marzo 2018- Exportaciones-Bultos: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/b9f4aa99-1527-4d2d-ade8-d79644396e8f/download/2018-mar-expo-bultos.rar)
- Marzo 2018- Exportaciones-Dtran: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/06bf9064-c291-4287-809f-68e8f29f434f/download/2018-mar-expo-dtran.rar)
- Abril 2018- Exportaciones: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/3a606399-1826-418e-804c-ffbd2f04acfe/download/2018-abril-expo.rar)
- Abril 2018- Exportaciones-BULTOS: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/592e9d4e-9561-4961-896c-e4ea4424cb3e/download/2018-abr-expo-bul.rar)
- Abril 2018- Exportaciones-Dtran: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/92cf2aad-9832-4901-bf99-786f3c315d8b/download/2018-abr-expo-dtran.rar)
- Mayo 2018 - Exportaciones: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/cc35ff98-16dc-4963-b503-2115f2309736/download/2018-may-expo.rar)
- Mayo 2018 - Exportaciones-BULTOS: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/eec705be-ff7d-44fa-9ee9-51d6af4a7bab/download/2018-may-expo-bultos.rar)
- Mayo 2018 - Exportaciones-Dtran: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/59becb1f-160a-4ddb-a04e-b1798d8b9e05/download/2018-may-expo-dtran.rar)
- 2018 JUN EXPO DTRAN: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/243f140e-f86f-48ed-9887-328e024415df/download/2018-jun-expo-dtran.rar)
- 2018 JUN EXPO: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/73df7c38-0a35-4fd6-944a-dd3327849f4e/download/2018-jun-expo.rar)
- 2018 JUNIO EXPO BUL: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/ab880f09-1eeb-4a78-bbf1-ad2f0b6d0564/download/2018-junio-expo-bul.rar)
- Julio 2018-Exportaciones: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/2bd36d97-085d-4961-bd4f-056768341f1e/download/julio-2018-exportaciones.rar)
- Julio 2018 – Exportaciones - Bultos: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/217859f3-e360-461c-9458-5418c004e52e/download/julio-2018-exportaciones-bultos.rar)
- Julio 2018 – Exportaciones - Dtran: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/5f113718-8dfc-4c57-9633-dcd14f937ae3/download/julio-2018-exportaciones-dtran.rar)
- Agosto 2018 - Exportaciones: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/b536900b-8929-4423-8ecf-af2e5f5e4d9c/download/agosto-2018-exportaciones.rar)
- Agosto 2018 - Exportaciones-BULTOS: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/4b21c3d9-ee1b-4923-b210-bffc90158954/download/agosto-2018-exportaciones-bultos.rar)
- Agosto 2018 - Exportaciones-Dtran: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/254cd928-b322-4299-b687-3a6ffba391bd/download/agosto-2018-exportaciones-dtran.rar)
- Septiembre 2018 – Exportaciones: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/907d7f3c-f93d-410e-b4e4-9cbf6a90ae4d/download/septiembre-2018-exportaciones.rar)
- Septiembre 2018 - Exportaciones-BULTOS: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/34776eb4-6085-4464-9ac1-747e5a3f4ce1/download/septiembre-2018-exportaciones-bultos.rar)
- Septiembre 2018 - Exportaciones-Dtran: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/1d22f9b1-7ff9-4140-b58e-3a391c6e112a/download/septiembre-2018-exportaciones-dtran.rar)
- Octubre 2018 – Exportaciones: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/db2537a7-3ade-4bfe-b930-0345d3517576/download/octubre-2018-dus-.rar)
- Octubre 2018 - Exportaciones-Dtran: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/facab9eb-968b-4864-91d4-eb51ac8f126b/download/octubre-2018-dus-doctran.rar)
- Octubre 2018 - Exportaciones-BULTOS: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/2e58b143-0780-4155-98b5-1043e5bb3b3f/download/octubre-2018-dus-bultos.rar)
- Noviembre 2018 - Exportaciones-BULTOS: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/cc74236f-0492-42db-8b83-b3fd2b01b85b/download/noviembre-2018-exportaciones-bultos.rar)
- Noviembre 2018 - Exportaciones-Dtran: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/3b57e9fe-47f0-49d0-ac7c-810d4ae5e003/download/noviembre-2018-exportaciones-dtran.rar)
- Noviembre 2018 - Exportaciones: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/f8dd9af4-a70e-4090-9b3c-f1e17b7916c3/download/noviembre-2018-exportaciones.rar)
- Diciembre 2018 - Exportaciones-BULTOS: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/c4ed6e0b-6839-4cc4-b672-8fe1c311aeda/download/diciembre-2018-exportacioes-bultos.rar)
- Diciembre 2018 - Exportaciones-Dtran: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/be871f07-89d6-4aea-b363-adacef9d3489/download/diciembre-2018-exportaciones-dtran.rar)
- Diciembre 2018 - Exportaciones: rar (https://datos.gob.cl/dataset/c9ddc990-53d9-4e50-86f0-d4b71cc6c803/resource/cc585c23-a2f4-4ffc-998b-2b1e46f567df/download/diciembre-2018-exportaciones.rar)
Nombre: Registro de Exportaciones 2024
Descripción: Muestra el registro de ítems correspondientes a los Documentos únicos de Salida (DUS) del año 2024. Registros mensuales. Formato comprimido  WinRar.
Recursos disponibles:
- Metadata Exportaciones: xlsx (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/df0c8f70-7582-481c-82d6-07d958ebb299/download/descripcion-y-estructura-de-datos-.xlsx)
- Exportaciones enero 2024: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/118906a7-a117-4aa0-829a-a7a9633e3acd/download/exportaciones-enero-2024.rar)
- Exportaciones enero 2024 - Bultos: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/1f2b1842-6d36-4642-8e2a-ee754b29058a/download/exportaciones-enero-2024-bultos.rar)
- Exportaciones enero 2024 - Documentos de Transporte: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/89fa74c5-e3a0-4fc8-9108-ebe9dce1d901/download/exportaciones-enero-2024-documentos-de-transporte.rar)
- Exportaciones febrero 2024: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/0e6a49ba-be6e-4b2c-8e4e-948c43c730ad/download/exportaciones-febrero-2024.rar)
- Exportaciones febrero 2024 - Bultos: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/33c7e3bd-0a30-4434-80f1-8735ad3754fb/download/exportaciones-febrero-2024-bultos.rar)
- Exportaciones febrero 2024 - Documentos de Transporte: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/9a05275d-660b-4a6b-83cb-0b30be2eb3e2/download/exportaciones-febrero-2024-documentos-de-transporte.rar)
- Exportaciones marzo 2024: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/16564df2-4fcf-425b-8bb2-ca77bb84244c/download/exportaciones-marzo-2024.rar)
- Exportaciones marzo 2024 - Bultos: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/44c3b4ca-174c-416e-9740-dfb6b1af264b/download/exportaciones-marzo-2024-bultos.rar)
- Exportaciones marzo 2024 - Documentos de Transporte: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/512bb6bb-e9a5-4500-8549-25cab34d9165/download/exportaciones-marzo-2024-documentos-de-transporte.rar)
- Exportaciones abril 2024: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/37bc765f-5a90-4766-8613-18741bd65e87/download/exportaciones-abril-2024.rar)
- Exportaciones abril 2024 - Bultos: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/95ea3d2a-a9b9-41f4-99aa-85504b27a359/download/exportaciones-abril-2024-bultos.rar)
- Exportaciones abril 2024 - Documentos de Transporte: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/f2c6fc0c-a7d1-45eb-a0eb-eb0b3591569d/download/exportaciones-abril-2024-documentos-de-transporte.rar)
- Exportaciones mayo 2024: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/53a4b5d7-d273-43bf-817f-7ef955efe0b2/download/exportaciones-mayo-2024.rar)
- Exportaciones mayo 2024 - Bultos: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/c0f37980-b644-466d-be0b-e8dfe13c928a/download/exportaciones-mayo-2024-bultos.rar)
- Exportaciones mayo 2024 - Documentos de Transporte.rar: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/6e6d5924-b597-4ad7-93a4-fae2fdcfdcc9/download/exportaciones-mayo-2024-documentos-de-transporte.rar)
- Exportaciones junio 2024: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/0ddc96e1-558a-46a9-a804-4a2bf41554db/download/exportaciones-junio-2024.rar)
- Exportaciones junio 2024 - Bultos: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/353d2e60-4786-46e1-8a08-210a6ba26c7b/download/exportaciones-junio-2024-bultos.rar)
- Exportaciones junio 2024 - Documentos de Transporte: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/e97ec893-fa7d-4eaa-89c2-ec3f8569c5d7/download/exportaciones-junio-2024-documentos-de-transporte.rar)
- Exportaciones julio 2024: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/b97eef91-6859-4f46-970d-e22995253f38/download/exportaciones-julio-2024.rar)
- Exportaciones julio 2024 - Bultos: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/f9778099-a861-47c8-9923-305d2a9ece4a/download/exportaciones-julio-2024-bultos.rar)
- Exportaciones julio 2024 - Documentos de Transporte: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/efac7ece-4bfd-43a4-9150-41837824935e/download/exportaciones-julio-2024-documentos-de-transporte.rar)
- Exportaciones agosto 2024: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/70f45b1c-59d2-4866-9050-4b86240a2701/download/exportaciones-agosto-2024.rar)
- Exportaciones agosto 2024 - Bultos: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/0d91dbd1-9ff0-4f9f-9b7d-a2a355659110/download/exportaciones-agosto-2024-bultos.rar)
- Exportaciones agosto 2024 - Documentos de Transporte: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/da981329-8a9f-437e-85a8-20ac11ec9178/download/exportaciones-agosto-2024-documentos-de-transporte.rar)
- Exportaciones septiembre 2024: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/819e3da1-0b18-4ed2-8660-60ba54bb4ced/download/exportaciones-septiembre-2024.rar)
- Exportaciones septiembre 2024 - Bultos: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/07f63433-bcb6-4935-9d3c-7749e9d02f5f/download/exportaciones-septiembre-2024-bultos.rar)
- Exportaciones septiembre 2024 - Documentos de Transporte: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/e13a026e-8697-4d93-84e8-c166cb1bffd5/download/exportaciones-septiembre-2024-documentos-de-transporte.rar)
- Exportaciones octubre 2024: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/754440f9-f46f-427d-94c2-85a6e7728c21/download/exportaciones-octubre-2024.rar)
- Exportaciones octubre 2024 – Bultos: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/f73d92c5-1723-4f47-9e97-455fc6b83108/download/exportaciones-octubre-2024-bultos.rar)
- Exportaciones octubre 2024 – Documentos de Transporte: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/edf44dfa-0334-46fa-907f-341b6bc75d35/download/exportaciones-octubre-2024-documentos-de-transporte.rar)
- Exportaciones noviembre 2024: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/7c32050c-2fdd-45ef-b676-77ef8f1272e8/download/exportaciones-noviembre-2024.rar)
- Exportaciones noviembre 2024 – Bultos: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/da10ad24-fbe2-49f2-bac7-74b05656f97e/download/exportaciones-noviembre-2024-bultos.rar)
- Exportaciones noviembre 2024 – Documentos de Transporte: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/935782a6-6418-4c90-ae8a-e4237abd3ded/download/exportaciones-noviembre-2024-documentos-de-transporte.rar)
- Exportaciones Diciembre 2024: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/6ceb52da-9b4c-4efa-84e0-a45c334d8e80/download/exportaciones-diciembre-2024.rar)
- Exportaciones Diciembre 2024 – Documentos de Transporte: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/451f33d9-96f3-47e3-91c6-45a975d3fe6f/download/exportaciones-diciembre-2024-documentos-de-transporte.rar)
- Exportaciones Diciembre 2024 – Bultos: rar (https://datos.gob.cl/dataset/1545f888-3490-466b-b815-60a0cd02ad23/resource/de726b8e-b336-40c2-96d7-69f9be2b18c1/download/exportaciones-diciembre-2024-bultos.rar)
Nombre: Registro de Exportación 2023
Descripción: Muestra el registro de ítems correspondientes a los Documentos únicos de Salida (DUS) del año 2023. Registros mensuales. Formato comprimido  WinRar.
Recursos disponibles:
- Metadata Exportaciones: xlsx (https://datos.gob.cl/dataset/d4f8a96f-c555-4f68-b0a9-261dbd34292d/resource/9ed0eb0a-5125-4681-bbea-dc8948038bbe/download/descripcion-y-estructura-de-datos-.xlsx)
- Exportaciones enero 2023: rar (https://datos.gob.cl/dataset/d4f8a96f-c555-4f68-b0a9-261dbd34292d/resource/6cb7d55a-9fa9-485c-b9ca-b8ae3df5ddb2/download/exportaciones-enero-2023.rar)
- Exportaciones enero 2023– Bultos: rar (https://datos.gob.cl/dataset/d4f8a96f-c555-4f68-b0a9-261dbd34292d/resource/5ae6c8ef-0b30-4f11-9359-49b32fb58fff/download/exportaciones-enero-2023-bultos.rar)
- Exportaciones enero 2023– Documentos de Transporte: rar (https://datos.gob.cl/dataset/d4f8a96f-c555-4f68-b0a9-261dbd34292d/resource/103a5c15-d485-42fe-a6fb-81edab79b682/download/exportaciones-enero-2023-documentos-de-transporte.rar)
- Exportaciones febrero 2023: rar (https://datos.gob.cl/dataset/d4f8a96f-c555-4f68-b0a9-261dbd34292d/resource/97290a1f-d867-4b86-a1b3-d992060725a5/download/exportaciones-febrero-2023.rar)
- Exportaciones febrero 2023– Bultos: rar (https://datos.gob.cl/dataset/d4f8a96f-c555-4f68-b0a9-261dbd34292d/resource/898c58dd-6396-466b-ac35-82a0294872ef/download/exportaciones-febrero-2023-bultos.rar)
- Exportaciones febrero| 2023– Documentos de Transporte: rar (https://datos.gob.cl/dataset/d4f8a96f-c555-4f68-b0a9-261dbd34292d/resource/8ce37c83-d297-4cac-a3c6-fa38914d9041/download/exportaciones-febrero-2023-documentos-de-transporte.rar)
- Exportaciones marzo 2023: rar (https://datos.gob.cl/dataset/d4f8a96f-c555-4f68-b0a9-261dbd34292d/resource/8e8aaf27-c556-4897-ab8c-02c50e6b6c25/download/exportaciones-marzo-2023.rar)
- Exportaciones marzo 2023– Bultos: rar (https://datos.gob.cl/dataset/d4f8a96f-c555-4f68-b0a9-261dbd34292d/resource/857281ec-4973-4f63-94ac-688ea39003a9/download/exportaciones-marzo-2023-bultos.rar)
- Exportaciones marzo 2023– Documentos de Transporte: rar (https://datos.gob.cl/dataset/d4f8a96f-c555-4f68-b0a9-261dbd34292d/resource/a97acf4b-b269-4021-8457-78ec3ae44f6f/download/exportaciones-marzo-2023-documentos-de-transporte.rar)
- Exportaciones abril 2023: rar (https://datos.gob.cl/dataset/d4f8a96f-c555-4f68-b0a9-261dbd34292d/resource/b7f6799d-960f-412f-9498-1df4ea0e7f80/download/exportaciones-abril-2023.rar)
- Exportaciones abril 2023– Bultos: rar (https://datos.gob.cl/dataset/d4f8a96f-c555-4f68-b0a9-261dbd34292d/resource/e1365b5f-e657-44aa-a3eb-7cfb0881304c/download/exportaciones-abril-2023-bultos.rar)
- Exportaciones abril 2023– Documentos de Transporte: rar (https://datos.gob.cl/dataset/d4f8a96f-c555-4f68-b0a9-261dbd34292d/resource/a83fd9dd-959e-4f55-b5e5-2ab9f9efa4de/download/exportaciones-abril-2023-documentos-de-transporte.rar)
- Exportaciones mayo 2023: rar (https://datos.gob.cl/dataset/d4f8a96f-c555-4f68-b0a9-261dbd34292d/resource/cd86a30a-b05b-414c-aae7-95d57b2ab95c/download/exportaciones-mayo-2023.rar)
- Exportaciones mayo 2023– Bultos: rar (https://datos.gob.cl/dataset/d4f8a96f-c555-4f68-b0a9-261dbd34292d/resource/7a5ad5ef-27ef-43ca-b400-2b2465d0a3d0/download/exportaciones-mayo-2023-bultos.rar)
- Exportaciones mayo 2023– Documentos de Transporte: rar (https://datos.gob.cl/dataset/d4f8a96f-c555-4f68-b0a9-261dbd34292d/resource/7021fd95-f847-4392-9dc5-22ff53e83974/download/exportaciones-mayo-2023-documentos-de-transporte.rar)
- Exportaciones junio 2023: rar (https://datos.gob.cl/dataset/d4f8a96f-c555-4f68-b0a9-261dbd34292d/resource/99217c2c-b083-41ae-9772-a9f73ebfba2f/download/exportaciones-junio-2023.rar)

Esta parte se ejecuta para extraer los archivos .rar y consolidar

In [ ]:
#Para colab
#!apt-get install unrar

In [2]:
import os
import tempfile
from pathlib import Path
import pandas as pd
import rarfile

In [6]:
aduanas_dir = Path(os.path.abspath(os.path.join(os.getcwd(), "..", "data", "aduanas")))
extract_dir = Path(tempfile.mkdtemp(prefix="extracted_files"))

# Specify the full path to the unrar.exe file
rarfile.UNRAR_TOOL = r"C:\Program Files\WinRAR\UnRAR.exe" #comentar si se trabaja con linux/unix

df_list = []

part01_files = sorted(aduanas_dir.glob("*.part01.rar"))

for rar_file in part01_files:
    with rarfile.RarFile(rar_file) as rar_archive:
        rar_archive.extractall(path=extract_dir)

txt_files = sorted(extract_dir.rglob("*.txt"))

for txt_file in txt_files:
    try:
        df_tmp = pd.read_csv(txt_file, sep=";", low_memory=False, encoding="latin-1")
    except Exception:
        df_tmp = pd.read_csv(txt_file, sep=",", low_memory=False, encoding="latin-1")
    df_tmp["archivo_origen"] = txt_file.name
    df_list.append(df_tmp)
    txt_file.unlink(missing_ok=True)

aduanas_df = pd.concat(df_list, ignore_index=True) if df_list else pd.DataFrame()

aduanas_df.to_csv(aduanas_dir / "aduanas_df.csv", sep= ';', index=False, encoding="utf-8")

ParserError: Error tokenizing data. C error: Expected 14 fields in line 65, saw 15

### 2.2 Banco Central de Chile
https://si3.bcentral.cl/Siete/es/Siete/API?respuesta=

In [ ]:
!pip install bcchapi

Collecting bcchapi
  Downloading bcchapi-1.1.2-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from bcchapi) (2.1.4)
Requirement already satisfied: requests>=2.0.1 in /usr/local/lib/python3.10/dist-packages (from bcchapi) (2.32.3)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->bcchapi) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->bcchapi) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->bcchapi) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->bcchapi) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.0.1->bcchapi) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.0.1->bcchapi) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.0.1->bcchapi) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.0.1->bcchapi) (2024.7.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->bcchapi) (1.16.0)
Downloading bcchapi-1.1.2-py3-none-any.whl (10 kB)
Installing collected packages: bcchapi
Successfully installed bcchapi-1.1.2

In [ ]:
import bcchapi

# Incluyendo credenciales explícitamente
# O bien llamando a un archivo
siete = bcchapi.Siete(file="credenciales.txt")

In [ ]:
siete.buscar("M1")

,seriesId,frequencyCode,spanishTitle,englishTitle,firstObservation,lastObservation,updatedAt,createdAt
0,F021.M1.PRO.N.CLP.0.M,MONTHLY,"Agregados monetarios nominales saldos, M1 (Mil...","Balances nominal monetary aggregates, M1",1986-01-01,2024-07-01,2024-08-07,2024-08-07
1,F021.M1.PRO.N.CLP.1.M,MONTHLY,"Agregados monetarios nominales saldos, M1 dese...","Balances nominal monetary aggregates, M1 seaso...",1986-01-01,2024-07-01,2024-08-07,2024-08-07
2,F021.M1.STO.N.CLP.0.M,MONTHLY,"M1; agregados monetarios nominales, promedios ...","M1; nominal monetary aggregates, averaged (bil...",1965-12-01,2024-07-01,2024-08-07,2024-08-07
3,F021.M1.STO.N.CLP.HIST.M,MONTHLY,"Agregados monetarios nominales promedios, M1, ...",Base monetaria y agregados monetarios privados...,1965-12-01,2014-12-01,2015-05-28,2015-02-09
4,F021.M1.STO.R.P96.0.M,MONTHLY,"Agregados monetarios promedios reales , M1","Average real monetary aggregates, M1",1986-01-01,2023-12-01,2024-01-08,2024-01-08
5,F021.M1.STO.R.P96.1.M,MONTHLY,"Agregados monetarios promedios reales , M1 des...","Average real monetary aggregates, seasonally a...",1986-01-01,2023-12-01,2024-01-08,2024-01-08
6,F021.M1.STO.R.P96R23.0.M,MONTHLY,"M1 : Stock : Real : Pesos del 1996, referencia...","M1: Stock: Real: 1996 pesos, reference 2023: N...",1986-01-01,2024-07-01,2024-08-08,2024-08-08
7,F021.M1.STO.R.P96R23.1.M,MONTHLY,"M1 : Stock : Real : Pesos del 1996, referencia...","M1: Stock: Real: 1996 pesos, reference 2023: S...",1986-01-01,2024-07-01,2024-08-08,2024-08-08
8,F021.M1.STO.N.CLP.0.D,DAILY,Base monetaria y agregados monetarios privados...,Components of M1 (billions of pesos). M1,2011-01-03,2024-07-31,2024-08-07,2024-08-07
9,F021.M1.STS.N.CLP.0.D,DAILY,Base monetaria y agregados monetarios privados...,Base monetaria y agregados monetarios privados...,1996-01-07,2024-08-07,2024-08-16,2024-08-16
10,F021.M1.PPIB18.N.CLP.0.T,QUARTERLY,"M1/PIB (M1 como porcentaje del PIB, últimos 12...","M1/GDP (M1 as percentage of GDP, last 12 month...",1996-10-01,2024-04-01,2024-08-19,2024-08-19

In [ ]:
series_bc = siete.cuadro(
  series=["F032.IMC.IND.Z.Z.EP18.Z.Z.0.M", "G073.IPC.IND.2018.M","F021.M1.STO.N.CLP.0.M"],
  nombres = ["imacec", "ipc","M1"],
  desde="2010-01-01",
  hasta="2024-07-01",
  #variacion=12,
  frecuencia="M",
  observado={"imacec":"mean", "ipc":"last", "M1":"mean"}
)

In [ ]:
series_bc = series_bc.fillna(0)
series_bc.head(50)

               imacec        ipc            M1
2010-01-31  72.478647  76.458780  13780.600000
2010-02-28  69.784256  76.673627  13876.100000
2010-03-31  75.714061  76.738097  14204.700000
2010-04-30  77.836154  77.092780  14333.800000
2010-05-31  77.265080  77.370183  15026.700000
2010-06-30  76.186444  77.370465  15322.400000
2010-07-31  74.112635  77.867485  15145.300000
2010-08-31  77.296543  77.790935  15125.600000
2010-09-30  75.050155  78.102046  15648.800000
2010-10-31  80.061679  78.178624  15449.000000
2010-11-30  82.742488  78.233650  15348.200000
2010-12-31  85.153296  78.325874  16105.400000
2011-01-31  78.010367  78.537898  16485.800000
2011-02-28  74.279065  78.718604  16097.900000
2011-03-31  84.796447  79.320558  16026.500000
2011-04-30  82.417455  79.573557  16301.500000
2011-05-31  82.970070  79.891725  16579.600000
2011-06-30  80.371445  80.027306  16707.000000
2011-07-31  77.225680  80.128912  16298.700000
2011-08-31  80.761007  80.258840  16532.000000
2011-09-30  78.670318  80.657742  16812.000000
2011-10-31  84.178776  81.049265  16918.100000
2011-11-30  86.446294  81.306442  16806.400000
2011-12-31  91.043493  81.801767  18009.100000
2012-01-31  82.488508  81.873766  18188.313000
2012-02-29  79.583913  82.191760  17736.091000
2012-03-31  89.288491  82.325895  17863.384000
2012-04-30  87.623529  82.367637  18269.813000
2012-05-31  88.038617  82.392904  18738.816000
2012-06-30  86.063196  82.148901  18430.396000
2012-07-31  82.963263  82.138100  18339.818000
2012-08-31  86.650826  82.319751  17808.110000
2012-09-30  82.730095  82.952429  18638.737000
2012-10-31  89.847446  83.415861  18312.797000
2012-11-30  91.596477  83.040175  18272.034000
2012-12-31  94.690431  83.018130  19598.416000
2013-01-31  86.555400  83.165705  20113.553000
2013-02-28  82.225784  83.263246  19635.841758
2013-03-31  92.977186  83.582811  19926.323373
2013-04-30  91.412940  83.178497  19991.962000
2013-05-31  90.696062  83.171388  20370.534000
2013-06-30  88.606093  83.703908  20773.986000
2013-07-31  85.534996  83.922140  20848.742550
2013-08-31  88.926432  84.124095  20444.907000
2013-09-30  85.273742  84.575619  21103.844909
2013-10-31  92.340598  84.696262  20400.657982
2013-11-30  94.497923  85.011592  20803.212132
2013-12-31  96.977894  85.520647  22111.893000
2014-01-31  88.060444  85.673733  22353.752700
2014-02-28  84.785719  86.090681  22108.398000

## Precios de los Combustibles - CNE
http://energiaabierta.cl/categorias-estadistica/hidrocarburos/?_sft_etiquetas-estadistica=precio

In [4]:
import bz2
from io import TextIOWrapper

cne_dir = os.path.abspath(os.path.join(os.getcwd(), "..", "data", "cne"))
bz2_files = sorted(
    [
        os.path.join(cne_dir, f)
        for f in os.listdir(cne_dir)
        if f.lower().endswith(".csv.bz2") or f.lower().endswith(".bz2")
    ]
)

cne_df_list = []
for file_path in bz2_files:
    with bz2.open(file_path, "rt", encoding="utf-8", errors="replace") as f:
        df_tmp = pd.read_csv(f, low_memory=False, sep = ';', decimal=',', encoding="latin-1")
    df_tmp["archivo_origen"] = os.path.basename(file_path)
    cne_df_list.append(df_tmp)

cne_df = pd.concat(cne_df_list, ignore_index=True) if cne_df_list else pd.DataFrame()

cne_df.head()

,id,razon_social,distribuidor,direccion_calle,direccion_numero,comuna,region,precio,fecha_actualizacion,combustible,latitud,longitud,archivo_origen,"codigo,razon_social,distribuidor,direccion,latitud,longitud,nom_comuna,nom_region,combustible,precio,unidad_cobro,atencion,fecha_actualizacion,hora_actualizacion,es_electrolinera,es_gasolinera"
0,co1312002,Sociedad Herrera Bravo Ltda,COPEC,Avenida Irarrázaval,5277,Ñuñoa,Metropolitana,759.0,2012-01-01,Gasolina 93,"-33,4540062109273","-70,57525992393493",2012.csv.bz2,NaN
1,pb630302,Distribuidora Dagnino Giacobbe y Cía. Ltda. 7...,Sin Bandera,Camino a Codegua Km,01,Chimbarongo,Gral. Bernardo O'Higgins,612.0,2012-12-13,Petroleo Diesel,"-34,71739081954427","-71,02941691875458",2012.csv.bz2,NaN
2,co120501,SOCIEDAD COMERCIAL IBAï¿½EZ Y NEGRON LTDA.,COPEC,"PANAMERICANA NORTE KM 1750, EX S. V",0,Pozo Almonte,Tarapacá,777.0,2012-12-06,Gasolina 95,"-21,09225805724834","-69,5928230881691",2012.csv.bz2,NaN
3,te1312301,Gilberto Zamorano Vega,SHELL,Holanda,2808,Providencia,Metropolitana,790.0,2012-12-06,Gasolina 97,"-33,44420837761395","-70,59720039367676",2012.csv.bz2,NaN
4,co1313201,PATRICIO REYES INFANTE Y CIA LTDA,COPEC,Av. Vitacura,6380,Vitacura,Metropolitana,873.0,2012-09-06,Gasolina 97,"-33,38974288164123","-70,57051241397858",2012.csv.bz2,NaN

In [5]:
cne_df.to_csv(os.path.join(cne_dir,'cne_df.csv'),
              sep = ';',
              index = False,
              encoding='utf-8')